FROM node:8-stretch

ENV PORT {{port}}
ENV NODE_HEAPDUMP_OPTIONS nosignal

WORKDIR "/app"

# Bundle app source
COPY . /app
COPY run-dev /bin
RUN apt-get update
RUN apt-get install bc

CMD ["/bin/bash"]

RUN chmod 777 /bin/run-dev && apt-get update && apt-get install bc
